---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]

suites:
  - name: default_composer
    run_list:
      - recipe[phploc::default]
    attributes:
      phploc:
        install_method: composer
